#' r -> Zotero
#'
#' Send citations from the \code{\link{citation}} function directly to Zotero
#' library through the Zotero JSON web API.
#'
#' @importFrom utils citation
#' @param pkg Package to cite.
#' @param manual_as_document Whether to export \code{MANUAL} bibtex entries as
#' a \code{document} rather than \code{software}. Defaults to \code{FALSE}.
#' @param verbose Whether to print verbose output to console. Defaults to
#' \code{TRUE}.
#' @author Ethan Bass
#' @return No return value. Function is called for its side effects.
#' @section Side effects:
#' Imports the citations generated by \code{citation} to a local Zotero library.

r2zotero <- function(pkg, manual_as_document = FALSE, verbose=TRUE) {
  zotero_is_running <- zotero_running()
  if (!zotero_is_running){
    stop()
  }
  schema <- get_zotero_schema()
  cit <- citation(pkg)
  lapply(cit, function(ct){
    autogenerated <- !is.null(ct$footer) && grepl("auto-generated", ct$footer)
      if (verbose && autogenerated){
        warning(sprintf("%s is autogenerated. Proceed with caution.", pkg), immediate. = TRUE)
      }
    response <- cit2zot(ct, manual_as_document = manual_as_document)
    if (httr::status_code(response) == "500"){
      warning()
    } else if (httr::status_code(response) == "201"){
      if (verbose)
        message(sprintf("%s successfully imported to Zotero library", pkg))
    }
    response
  }) |> invisible()
  # purrr::imap(cit, function(ct, i){
  #   autogenerated <- !is.null(ct$footer) && grepl("auto-generated", ct$footer)
  #   if (verbose && autogenerated){
  #     warning(sprintf("%s (%d) is autogenerated. Proceed with caution.", pkg, i), immediate. = TRUE)
  #   }
  #   response <- cit2zot(ct, manual_as_document = manual_as_document)
  #   if (httr::status_code(response) == "500"){
  #     warning()
  #   } else if (httr::status_code(response) == "201"){
  #     if (verbose)
  #       message(sprintf("%s (%d) successfully imported to Zotero library", pkg, i))
  #   }
  #   response
  # }) |> invisible()
}

#' cit -> Zot
#' @importFrom utils toBibtex
#' @noRd
#' @author Ethan Bass

cit2zot <- function(cit, manual_as_document = FALSE){
  bib <- toBibtex(cit)
  zot_df <- bib2zot_df(bib, manual_as_document = manual_as_document)

  zot_item <- as.list(zot_df[1, ])
  zot_item$creators <- zot_item$creators[[1]]

  # payload <- list(items = list(as.list(zot_df)))
  payload <- list(items = list(zot_item))
  # cat(jsonlite::toJSON(payload, auto_unbox = TRUE, pretty = TRUE))

  response <- httr::POST("http://localhost:23119/connector/saveItems",
                         body = jsonlite::toJSON(payload, auto_unbox = TRUE),
                         httr::add_headers("Content-Type" = "application/json"))
  response
}

#' Check if Zotero is running
#' @noRd
zotero_running <- function() {
  tryCatch({
    response <- httr::GET("http://localhost:23119/connector/ping")
    return(httr::status_code(response) == 200)
  }, error = function(e) FALSE)
}
